# Generated by Django 5.2.6 on 2026-03-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_secondary_admin',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
