# Generated by Django 5.2.6 on 2026-03-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_is_secondary_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_secondary_admin',
            field=models.BooleanField(default=False),
        ),
    ]
