# Generated by Django 5.2.6 on 2026-03-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholars_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsevent',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
