# Generated by Django 5.2.6 on 2026-03-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholars_main', '0002_newsevent_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
