# Generated by Django 5.2.6 on 2026-03-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholars_main', '0003_alter_newsevent_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsevent',
            name='type',
            field=models.CharField(blank=True, choices=[('news', 'News'), ('event', 'Event')], default='news', max_length=10, null=True),
        ),
    ]
