# Generated by Django 5.2.6 on 2026-03-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholars_main', '0005_singleunique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleunique',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='others'),
        ),
    ]
