# Generated by Django 5.2.6 on 2026-03-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholars_main', '0006_alter_singleunique_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleunique',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='singleunique',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
